#!/bin/bash
# SettleMap Emergency Reference — Mac/Linux
# Run: bash scripts/emergency-notes.sh
# This script only DISPLAYS information and opens links. It does NOT make any changes.

echo ""
echo "========================================================"
echo " SettleMap Emergency Reference"
echo " Version: V12.12.9"
echo "========================================================"
echo ""
echo "IMPORTANT: This script only shows information."
echo "All actual changes must be made in the Vercel Dashboard."
echo ""
echo "========================================================"
echo " QUICK LINKS"
echo "========================================================"
echo ""
echo "  Live site:       https://videshflow-demo.vercel.app"
echo "  Health check:    https://videshflow-demo.vercel.app/api/stripe/health"
echo "  Vercel env vars: https://vercel.com/salestradzlah-codes-projects/videshflow-demo/settings/environment-variables"
echo "  Vercel deploys:  https://vercel.com/salestradzlah-codes-projects/videshflow-demo/deployments"
echo "  Stripe:          https://dashboard.stripe.com"
echo "  GitHub repo:     https://github.com/salestradzlah-code/videshflow-demo"
echo ""
echo "========================================================"
echo " EMERGENCY ACTIONS — ALL DONE IN VERCEL DASHBOARD"
echo "========================================================"
echo ""
echo "1. PAUSE PAYMENTS:"
echo "   → Go to Vercel env vars"
echo "   → Find PAYMENTS_GLOBAL_PAUSED"
echo "   → Change value to: true"
echo "   → Save → Redeploy"
echo ""
echo "2. PAUSE AI ASSISTANT:"
echo "   → Go to Vercel env vars"
echo "   → Find AI_GLOBAL_PAUSED"
echo "   → Change value to: true"
echo "   → Save → Redeploy"
echo ""
echo "3. TURN ON MAINTENANCE MODE:"
echo "   → Go to Vercel env vars"
echo "   → Find SITE_MAINTENANCE_MODE"
echo "   → Change value to: true"
echo "   → Save → Redeploy"
echo ""
echo "4. ROLL BACK TO PREVIOUS VERSION:"
echo "   → Go to Vercel Deployments"
echo "   → Find the last green (working) deployment"
echo "   → Click ... → Redeploy"
echo "   → Do NOT change build settings"
echo ""
echo "========================================================"
echo " WHAT NOT TO DO"
echo "========================================================"
echo ""
echo "  ✗ Do not delete Vercel env variables (only change values)"
echo "  ✗ Do not delete Stripe products or prices"
echo "  ✗ Do not change DNS settings"
echo "  ✗ Do not commit .env.local to GitHub"
echo "  ✗ Do not share secret keys in email or chat"
echo "  ✗ Do not run refunds for amounts the customer did not pay"
echo ""
echo "========================================================"
echo " CONTACT"
echo "========================================================"
echo ""
echo "  Ashish: ashishabokil@gmail.com (WhatsApp for emergencies)"
echo ""

# Open health check in browser
echo "Opening health check in browser..."
if [[ "$OSTYPE" == "darwin"* ]]; then
  open "https://videshflow-demo.vercel.app/api/stripe/health"
fi

echo ""
